# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Luis Puerto"
title_separator          : "|"
name                     : "Luis Puerto"
description              : "Forestry | Research | GIS | Remote Sensing"
url                      : "https://luisspuerto.net"
baseurl                  : # "/blog"
repository               : "luisspuerto/luisspuerto.net"
teaser                   : "/assets/images/pages/teaser-default.jpg"
breadcrumbs              : # false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : "luisspuerto-net" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
    api_key              : "Pl2s6WZnj9RWDS428ro3EiD9nz6QkH91pNswUepzxrSgOmSG0byByPNPR4Tdc6Zp"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                : "6Le3UGYUAAAAAGCV3MSUS-8eLKv8z1_QoRKY7nFG"
  secret                 : "kmvLr5CVHi1aUyL3yL2SYTe1qIig7fbb0mgBAw+Et1J2OgJ+L8amh1FXbogoY5KnFS1UFUh4VyGyCyOBsjpVOqcHN6BhtC6kORA5VzUscGyHCUlql636m2C5qaOkGPzpaxAuX4XPAH3LLk1eqTWZF6d3Ieeappzz2m6yDRGl0eY="
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          :  "algolia" # google # lunr (default), algolia, google
algolia:
  application_id         : "NSAWFR2G1K" # YOUR_APPLICATION_ID
  index_name             : "luisspuerto-net" # YOUR_INDEX_NAME
  search_only_api_key    : "b63bbd39b0bf76207cf9bebdb9c2b7dd" # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : "015834395021109974254:iwyitsyv8ii" # YOUR_SEARCH_ENGINE_ID
  instant_search         : true # false (default), true
# SEO Related
google_site_verification : "2AztHRijor0b6F_0DFrw0mYxhQVvLKT3rlFp7PxTS1M"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : "lpuerto"
facebook:
  username               :
  app_id                 :
  publisher              :
linkedin:
  username               : "lpuerto"
og_image                 : /assets/images/pages/header-splash.jpg
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - https://twitter.com/lpuerto
    - https://www.linkedin.com/in/lpuerto
    - https://github.com/luisspuerto
    - https://www.flickr.com/photos/luisspuerto

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-1931812-1"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Luis Puerto"
  avatar           : "/assets/images/pages/20121231-035-ol.jpg"
  bio              : "Born in Ponferrada, Spain. A Forest Engineer interested
                      in Science and Technology. Fascinated about almost everything"
  location         : "🇪🇺🇪🇸🇸🇪🇫🇮🇺🇸"
  email            : "luis@luisspuerto.net"
  uri              : # "/aboutme"
  home             : "/aboutme" # null (default), "absolute or relative url to link to author home"
  bitbucket        : # "luisspuerto"
  codepen          :
  dribbble         :
  flickr           : "luisspuerto"
  facebook         : # "lpuerto"
  foursquare       :
  github           : "luisspuerto"
  gitlab           : # "luisspuerto"
  google_plus      : # "+LuisPuerto"
  keybase          :
  instagram        : "lpuerto"
  lastfm           :
  linkedin         : "lpuerto"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "6888648/lpuerto" # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           : "luisspuerto"
  twitter          : "lpuerto"
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/LuisPuerto" # "https://youtube.com/c/MichaelRoseDesign"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README.*
  - staticman.yml
  - tmp
  - TODO.*
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - /resources # different files I use for the blog and the web.
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      header:
        show_overlay_excerpt: false
